homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include config/customization.yaml

frontend:

# updater:
discovery:
# history:

logbook:
  exclude:
    domains:
      - sun

sun:

recorder:
  purge_days: 8

automation: !include_dir_list config/automations
group: !include config/groups.yaml
input_boolean: !include config/input_booleans.yaml
sensor: !include_dir_merge_list config/sensors

http:
  api_password: !secret http_password
  # ssl_certificate: /etc/letsencrypt/live/gngr-hass.duckdns.org/fullchain.pem
  # ssl_key: /etc/letsencrypt/live/gngr-hass.duckdns.org/privkey.pem

zwave:
  usb_path: /dev/ttyUSB-Zwave
