homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include config/customization.yaml

frontend:
updater:
discovery:
history:
logbook:
  exclude:
    domains:
      - sun
    # entities:
    #   - sensor.pws_weather
    #   - sensor.pws_temp_c
    #   - sensor.pws_wind_dir
    #   - sensor.pws_wind_kph
sun:

recorder:
  purge_days: 7
  db_url: !secret mysql # mysql://dbuser:password@localhost/dbname

http: !include config/http.yaml
automation: !include_dir_list config/automations
group: !include config/groups.yaml
input_boolean: !include config/input_booleans.yaml
scene: !include_dir_merge_list config/scenes
script: !include_dir_merge_named config/scripts
sensor: !include_dir_merge_list config/sensors

notify:
  name: pushbullet
  platform: pushbullet
  api_key: !secret pushbullet_api

zwave:
  usb_path: /dev/ttyUSB-Zwave
