homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include config/customization.yaml

frontend:

updater:
discovery:
history:

logbook:
  exclude:
    domains:
      - sun
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_c
      - sensor.pws_wind_dir
      - sensor.pws_wind_kph

sun:

recorder:
  purge_days: 7
  db_url: !secret mysql # mysql://dbuser:password@localhost/dbname

automation: !include_dir_list config/automations
group: !include config/groups.yaml
input_boolean: !include config/input_booleans.yaml
sensor: !include_dir_merge_list config/sensors

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

zwave:
  usb_path: /dev/ttyUSB-Zwave
