hue_flash_green:
  alias: "Flash hue livingroom lights green"
  sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_flash_green
    - delay:
        seconds: 15
    - service: light.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Ontspannen"

# Todo
# - return light to previous state (on/off/scene)