hue_flash_blue:
  alias: "Flash hue livingroom lights blue"
  sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_flash_blauw
    - delay:
        seconds: 15
    - service: light.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Ontspannen"

# Todo
# - return light to previous state (on/off/scene)