alias: "Tuinverlichting aan na zonsondergang"
trigger:
  platform: sun
  event: sunset
condition:
  condition: state
  entity_id: 'input_boolean.auto_backyard_lights_on'
  state: 'on'
action:
  service: switch.turn_on
  entity_id: group.backyard