alias: Washingmachine busy
trigger:
  - platform: numeric_state
    entity_id: !secret dryer_power_usage
    below: 99
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.dryer_busy