alias: Dryer done notification
trigger:
  - platform: state
    entity_id: input_boolean.dryer_busy
    state: 'off'
condition:
  - condition: state
    entity_id: input_boolean.dryer_busy
    state: 'off'
action:
  - service: script.hue_flash