alias: Dryer done notification
trigger:
  - platform: state
    entity_id: input_boolean.dryer_busy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: !secret livingroom_light
    state: 'on'
action:
  - service: script.hue_flash_green