alias: 'Woonkamer uit om 00:00'
trigger:
  platform: time
  after: '23:59:00'
condition:
  condition: state
  entity_id: 'input_boolean.auto_livingroom_lights_off'
  state: 'off'
action:
  service: switch.turn_off
  entity_id: group.livingroom