alias: Washmingmachine done notification
trigger:
  - platform: state
    entity_id: input_boolean.washingmachine_busy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
action:
  - service: script.hue_flash