# Test MIB number on CMD
# snmpget -v1 -c public <ip nas> <MIB>

# Name
# - platform: snmp
#   name: "Synology NAS - Name"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.6574.1.5.1.0

# DSM
# - platform: snmp
#   name: "Synology NAS - DSM"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.6574.1.5.3.0

# - platform: snmp
#   name: "Synology NAS - Upgrade"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.6574.1.5.4.0

# - platform: template
#   sensors:
#       tpl_synology_nas_upgrade:
#         friendly_name: "DSM"
#         value_template: >-
#             {%- if is_state("sensor.synology_nas__upgrade", "1") %}
#                 {{ states("sensor.synology_nas__dsm") }} - Update available
#             {% else %}
#                 {{ states("sensor.synology_nas__dsm") }}
#             {%- endif %}
#         entity_id: sensor.synology_nas__dsm

# Temp
# - platform: snmp
#   name: "Synology NAS - Temp"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.6574.1.2.0
#   unit_of_measurement: "°C"

# Memory
# - platform: snmp
#   name: "Synology NAS - Memory"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.2021.4.5.0

# - platform: snmp
#   name: "Synology NAS - Memory available"
#   host: !secret nas_ip
#   community: public
#   baseoid: .1.3.6.1.4.1.2021.4.6.0

# - platform: template
#   sensors:
#       tpl_synology_nas_memory:
#         friendly_name: "Memory"
#         value_template: "{{ ((states('sensor.synology_nas__memory_available')|float) / 1024)|round(2) }} Mb / {{ ((states('sensor.synology_nas__memory')|float) / 1024)|round(2) }} Mb"
#         entity_id: sensor.synology_nas__memory



# Volume 1
# .1.3.6.1.2.1.25.2.3.1.4.38 - HD Unit
# .1.3.6.1.2.1.25.2.3.1.5.38 - HD Total
# .1.3.6.1.2.1.25.2.3.1.6.38 - HD Used
# HDFree = $((($HDTotal - $HDUsed) * $HDUnit / 1024 / 1024 / 1024))

# Free space volume1 (Percentage)
# .1.3.6.1.2.1.25.2.3.1.5.38 - HDTotal
# .1.3.6.1.2.1.25.2.3.1.6.38 - HDUsed
# HDFreePerc= $((($HDUsed * 100) / $HDTotal))

# Volume 2
# .1.3.6.1.2.1.25.2.3.1.4.40 - HD Unit
# .1.3.6.1.2.1.25.2.3.1.5.40 - HD Total
# .1.3.6.1.2.1.25.2.3.1.6.40 - HD Used
# HDFree = $((($HDTotal - $HDUsed) * $HDUnit / 1024 / 1024 / 1024))

# Free space volume 2 (Percentage)
# .1.3.6.1.2.1.25.2.3.1.5.40 - HDTotal
# .1.3.6.1.2.1.25.2.3.1.6.40 - HDUsed
# HDFreePerc= $((($HDUsed * 100) / $HDTotal))