# Weer
sun.sun:
    hidden: true

sensor.pws_weather:
    friendly_name: " "
sensor.pws_temp_c:
    friendly_name: "Temperatuur"
    icon: "mdi:thermometer-lines"
sensor.pws_wind_dir:
    friendly_name: "Windrichting"
    icon: "mdi:compass-outline"
sensor.pws_wind_kph:
    friendly_name: "Windsnelheid"
    icon: "mdi:weather-windy"

# Bewegingssensor
binary_sensor.neo_coolcam_unknown_type0003_id1083_sensor_4:
    friendly_name: "Bewegingssensor"
    icon: "mdi:walk"
sensor.neo_coolcam_unknown_type0003_id1083_alarm_level_4:
    hidden: true
sensor.neo_coolcam_unknown_type0003_id1083_alarm_type_4:
    hidden: true
sensor.neo_coolcam_unknown_type0003_id1083_burglar_4:
    hidden: true
sensor.neo_coolcam_unknown_type0003_id1083_luminance_4:
    friendly_name: "Lichtsterkte"
    icon: "mdi:eye"
sensor.neo_coolcam_unknown_type0003_id1083_sourcenodeid_4:
    hidden: true

# Woonkamer
switch.greenwave_powernode_1_port_switch_2:
    friendly_name: "Lamp"
    icon: "mdi:lightbulb-outline"
sensor.greenwave_powernode_1_port_switch_2:
    friendly_name: "Lamp"
    hidden: true
sensor.greenwave_powernode_1_port_power_2:
    hidden: true
sensor.greenwave_powernode_1_port_energy_2:
    hidden: true
sensor.greenwave_powernode_1_port_previous_reading_2:
    hidden: true
sensor.__alarm_level_6:
    hidden: true
sensor.__alarm_type_6:
    hidden: true

# Achtertuin
switch.greenwave_powernode_1_port_switch_3:
    friendly_name: "Led lampjes"
    icon: "mdi:led-outline"
sensor.greenwave_powernode_1_port_energy_3:
    friendly_name: "Led lampjes"
    hidden: true
sensor.greenwave_powernode_1_port_power_3:
    hidden: true
sensor.greenwave_powernode_1_port_previous_reading_3:
    hidden: true

# Schuur
sensor.neo_coolcam_power_plug_12a_alarm_level_6:
   hidden: true
sensor.neo_coolcam_power_plug_12a_alarm_type_6:
    hidden: true
switch.neo_coolcam_power_plug_12a_switch_6:
    friendly_name: "Wasmachine"
    icon: "mdi:basket-fill"
sensor.neo_coolcam_power_plug_12a_current_6:
    hidden: true
sensor.neo_coolcam_power_plug_12a_energy_6:
    hidden: true
sensor.neo_coolcam_power_plug_12a_power_6:
    friendly_name: "Wasmachine Watt"
sensor.neo_coolcam_power_plug_12a_power_management_6:
    hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_6:
    hidden: true
sensor.neo_coolcam_power_plug_12a_sourcenodeid_6:
    hidden: true
sensor.neo_coolcam_power_plug_12a_voltage_6:
    hidden: true

# Reistijd
sensor.sjors_heenreis:
    icon: "mdi:traffic-light"
sensor.sjors_terugreis:
    icon: "mdi:traffic-light"
sensor.saskia_heenreis:
    icon: "mdi:traffic-light"
sensor.saskia_terugreis:
    icon: "mdi:traffic-light"

#Speedtest
sensor.speedtest_download:
    icon: "mdi:download"
    friendly_name: "Download"
sensor.speedtest_upload:
    icon: "mdi:upload"
    friendly_name: "Upload"
sensor.speedtest_ping:
    icon: "mdi:timer"
    friendly_name: "Ping"