# Tabs
default_view:
  view: yes
  entities:
    - group.livingroom
    - group.backyard
    - group.shed
    - group.traveltime
    - group.weather

network_view:
  view: yes
  icon: "mdi:lan"
  entities:
    - group.network

automation_view:
  view: yes
  icon: "mdi:auto-fix"
  entities:
    - group.automation

# Groups
livingroom:
  name: Woonkamer
  entities:
    - !secret livingroom_light_toggle
    - !secret livingroom_motion
    - !secret livingroom_lux

backyard:
  name: Achtertuin
  entities:
    - !secret backyard_light_toggle

shed:
  name: Schuur
  entities:
    - !secret shed_washingmachine_power_toggle
    - !secret shed_washingmachine_power_usage

travel-time:
  name: Reistijd
  entities:
    - sensor.sjors_heenreis
    - sensor.sjors_terugreis
    - sensor.saskia_heenreis
    - sensor.saskia_terugreis

weather:
  name: Weer
  entities:
    - sensor.pws_weather
    - sensor.pws_temp_c
    - sensor.pws_wind_dir
    - sensor.pws_wind_kph

network:
  name: Netwerk
  entities:
    - sensor.speedtest_upload
    - sensor.speedtest_download
    - sensor.speedtest_ping

automation:
  name: Automagisch
  entities:
    - input_boolean.auto_livingroom_lights_on
    - input_boolean.auto_livingroom_lights_off
    - input_boolean.auto_backyard_lights_on
    - input_boolean.auto_backyard_lights_off