# Tabs
default_view:
  view: yes
  entities:
    - group.livingroom
    - group.backyard
    - group.shed
    - group.traveltime
    - group.weather

network_view:
  name: Netwerk
  view: yes
  icon: "mdi:lan"
  entities:
    - group.network

# Groups
livingroom:
  name: Woonkamer
  entities:
    - switch.greenwave_powernode_1_port_switch_2
    - binary_sensor.neo_coolcam_unknown_type0003_id1083_sensor_4
    - sensor.neo_coolcam_unknown_type0003_id1083_luminance_4

backyard:
  name: Achtertuin
  entities:
    - switch.greenwave_powernode_1_port_switch_3

shed:
  name: Schuur
  entities:
    - switch.neo_coolcam_power_plug_12a_switch_6
    - sensor.neo_coolcam_power_plug_12a_power_6

travel-time:
  name: Reistijd
  entities:
    - sensor.sjors_heenreis
    - sensor.sjors_terugreis
    - sensor.saskia_heenreis
    - sensor.saskia_terugreis

weather:
  name: Weer
  entities:
    - sensor.pws_weather
    - sensor.pws_temp_c
    - sensor.pws_wind_dir
    - sensor.pws_wind_kph

network:
  name: Netwerk
  entities:
    - sensor.speedtest_upload
    - sensor.speedtest_download
    - sensor.speedtest_ping