# Tabs
default_view:
  view: yes
  entities:
    - group.livingroom
    - group.backyard
    - group.shed
    - group.traveltime
    - group.weather

automation_view:
  view: yes
  icon: "mdi:auto-fix"
  entities:
    - group.automation

# Groups
livingroom:
  name: Woonkamer
  entities:
    - !secret livingroom_light_toggle
    - !secret livingroom_motion
    - !secret livingroom_lux

backyard:
  name: Achtertuin
  entities:
    - !secret backyard_light_toggle

shed:
  name: Schuur
  entities:
    - !secret shed_washingmachine_power_toggle
    - !secret shed_washingmachine_power_usage
    - input_boolean.washingmachine_busy
    - !secret dryer_power_toggle
    - !secret dryer_power_usage
    - input_boolean.dryer_busy

travel-time:
  name: Reistijd
  entities:
    - sensor.sjors_heenreis
    - sensor.sjors_terugreis
    - sensor.saskia_heenreis
    - sensor.saskia_terugreis

weather:
  name: Weer
  entities:
    - sensor.pws_weather
    - sensor.pws_temp_c
    - sensor.pws_wind_dir
    - sensor.pws_wind_kph

automation:
  name: Automagisch
  entities:
    - input_boolean.auto_livingroom_lights_on
    - input_boolean.auto_livingroom_lights_off
    - input_boolean.auto_backyard_lights_on
    - input_boolean.auto_backyard_lights_off