- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload

- platform: google_travel_time
  name: "Sjors heenreis"
  api_key: !secret google_travel_time_api
  origin: !secret google_travel_time_home
  destination: !secret google_travel_time_work_sjors
  options:
    mode: driving

- platform: google_travel_time
  name: "Sjors terugreis"
  api_key: !secret google_travel_time_api
  origin: !secret google_travel_time_work_sjors
  destination: !secret google_travel_time_home
  options:
    mode: driving

- platform: google_travel_time
  name: "Saskia heenreis"
  api_key: !secret google_travel_time_api
  origin: !secret google_travel_time_home
  destination: !secret google_travel_time_work_saskia
  options:
    mode: driving

- platform: google_travel_time
  name: "Saskia terugreis"
  api_key: !secret google_travel_time_api
  origin: !secret google_travel_time_work_saskia
  destination: !secret google_travel_time_home
  options:
    mode: driving

- platform: wunderground
  api_key: !secret wunderground_api
  pws_id: !secret wunderground_pws_id
  monitored_conditions:
    - weather
    #- temp_f
    - temp_c
    #- station_id
    #- feelslike_c
    #- feelslike_f
    #- feelslike_string
    #- heat_index_c
    #- heat_index_f
    #- heat_index_string
    #- dewpoint_c
    #- dewpoint_f
    #- dewpoint_string
    - wind_kph
    #- wind_mph
    #- UV
    #- pressure_in
    #- pressure_mb
    - wind_dir
    #- wind_string
    #- relative_humidity
    #- visibility_mi
    #- visibility_km
    #- precip_today_in
    #- precip_today_metric
    #- precip_today_string
    #- solarradiation


- platform: snmp
  name: "Synology NAS - Name"
  host: !secret nas_ip
  community: public
  baseoid: .1.3.6.1.4.1.6574.1.5.1.0

- platform: snmp
  name: "Synology NAS - Temp"
  host: !secret nas_ip
  community: public
  baseoid: .1.3.6.1.4.1.6574.1.2.0
  unit_of_measurement: "°C"

- platform: snmp
  name: "Synology NAS - DSM version"
  host: !secret nas_ip
  community: public
  baseoid: .1.3.6.1.4.1.6574.1.5.3.0

- platform: snmp
  name: "Synology NAS - DSM upgrade available"
  host: !secret nas_ip
  community: public
  baseoid: .1.3.6.1.4.1.6574.1.5.4.0

# .1.3.6.1.4.1.6574.1.2.0 - DiskStation temp
# .1.3.6.1.4.1.6574.1.5.1.0 - DiskStation name
# .1.3.6.1.4.1.6574.1.5.3.0 - DiskStation DMS version
# .1.3.6.1.4.1.6574.1.5.4.0 - DiskStation DMS upgrade available

# .1.3.6.1.4.1.2021.4.6.0 - Memory available (bytes, dus delen door 1024 voor mb)
# .1.3.6.1.4.1.2021.11.9.0 - CPU User
# .1.3.6.1.4.1.2021.11.10.0 - CPU System

# Volume 1
# .1.3.6.1.2.1.25.2.3.1.4.38 - HD Unit
# .1.3.6.1.2.1.25.2.3.1.5.38 - HD Total
# .1.3.6.1.2.1.25.2.3.1.6.38 - HD Used
# HDFree = $((($HDTotal - $HDUsed) * $HDUnit / 1024 / 1024 / 1024))


# Free space volume1 (Percentage)
# .1.3.6.1.2.1.25.2.3.1.5.38 - HDTotal
# .1.3.6.1.2.1.25.2.3.1.6.38 - HDUsed
# HDFreePerc= $((($HDUsed * 100) / $HDTotal))

# Volume 2
# .1.3.6.1.2.1.25.2.3.1.4.40 - HD Unit
# .1.3.6.1.2.1.25.2.3.1.5.40 - HD Total
# .1.3.6.1.2.1.25.2.3.1.6.40 - HD Used
# HDFree = $((($HDTotal - $HDUsed) * $HDUnit / 1024 / 1024 / 1024))

# Free space volume 2 (Percentage)
# .1.3.6.1.2.1.25.2.3.1.5.40 - HDTotal
# .1.3.6.1.2.1.25.2.3.1.6.40 - HDUsed
# HDFreePerc= $((($HDUsed * 100) / $HDTotal))